# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
  - port: 3010
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: scripts/build.sh
    command: gp sync-done build
    name: Build
  - command: gp sync-await build && npm start --prefix server
    name: Server
  - command: gp sync-await build && npm start --prefix client
    name: Client
